version: '3.8'
name: 'chatapp'

services:
  backend:
    build:
      context: backend
      #dockerfile: Prebuild.Dockerfile
    container_name: chatapp-backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    links:
      - 'database:database'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:postgresql://database:5432/chatapp
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - database-network
      - frontend-network

  frontend:
    build: frontend
    container_name: chatapp-frontend
    ports:
      - '80:80'
    networks:
      - frontend-network

  database:
    image: postgres
    container_name: chatapp-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chatapp-database:/var/lib/postgresql/data
    networks:
      - database-network
    restart: unless-stopped

volumes:
  chatapp-database:
    name: database

networks:
  database-network:
    name: database-network
  frontend-network:
    name: frontend-network
